##########################
#        Login           #
##########################

### S'inscrire
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "user42",
  "password": "je suis le roi du mondE1!#é",
  "validation": "je suis le roi du mondE1!#é"
}

### Se connecter
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "user42",
  "password": "je suis le roi du mondE1!#é"
}

##########################
#        Home            #
##########################
GET http://localhost:3000/

##########################
#        Teams           #
##########################

### Liste des teams (get /teams)
GET http://localhost:3000/teams

### Ajouter une team (post /teams)
POST http://localhost:3000/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3NjE3NDcwMTgsImV4cCI6MTc2MTc2MTQxOH0.b7CnLerXCkopnw90KPMaiZPbq3mH_kel-5P7VvYFUVQ 

{
  "name": "Nouvelle équipe",
  "description": "La nouvelle équipe de pokémons @#!6'"
}

### Modal d'une team (get /teams/:id)
GET http://localhost:3000/teams/5

### Supprimer une team (delete /teams/:id)
DELETE http://localhost:3000/teams/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3NjE3NDcwMTgsImV4cCI6MTc2MTc2MTQxOH0.b7CnLerXCkopnw90KPMaiZPbq3mH_kel-5P7VvYFUVQ 

### Modifier le nom d'une team (update /teams/:id)
PATCH http://localhost:3000/teams/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3NjE3NDcwMTgsImV4cCI6MTc2MTc2MTQxOH0.b7CnLerXCkopnw90KPMaiZPbq3mH_kel-5P7VvYFUVQ 


{
  "name": "Team modifié"
}

### Ajouter un pokemon à une team (post /teams/:teamId/pokemon/pokemon/:id)
PUT http://localhost:3000/teams/7/pokemons/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3NjE3NDcwMTgsImV4cCI6MTc2MTc2MTQxOH0.b7CnLerXCkopnw90KPMaiZPbq3mH_kel-5P7VvYFUVQ 


### Supprimer un pokemon à une team (post /teams/:teamId/pokemon/pokemon/:id)
DELETE http://localhost:3000/teams/7/pokemons/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3NjE3NDcwMTgsImV4cCI6MTc2MTc2MTQxOH0.b7CnLerXCkopnw90KPMaiZPbq3mH_kel-5P7VvYFUVQ 


##########################
#        Pokemons        #
##########################

### Lister les pokemons (get /pokemons)
GET http://localhost:3000/pokemons

### Modal d'un pokemon (get /pokemons/:id ou pokemon/:name)
GET http://localhost:3000/pokemons/drac

### Comparer deux pokemons (get /pokemons/:id/:idToCompare)
GET http://localhost:3000/pokemons/compare/1/2

#########Votes############

### Voter pour une pokemon (put /pokemons/:id/votes)
PUT http://localhost:3000/pokemons/2/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3NjE3NDcwMTgsImV4cCI6MTc2MTc2MTQxOH0.b7CnLerXCkopnw90KPMaiZPbq3mH_kel-5P7VvYFUVQ 

### Unvoter pour une pokemon (put /pokemons/:id/votes)
DELETE  http://localhost:3000/pokemons/3/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE3NjE3NDcwMTgsImV4cCI6MTc2MTc2MTQxOH0.b7CnLerXCkopnw90KPMaiZPbq3mH_kel-5P7VvYFUVQ 

### Afficher le nombre de votes pour un pokemons (get /pokemon/:id/votes)
GET http://localhost:3000/pokemons/2/votes

### Afficher le podium (get /pokemons/votes)
GET http://localhost:3000/pokemons/votes

##########################
#        Types           #
##########################

### Lister les types (get /types)
GET http://localhost:3000/types

### Modal d'un type(get /types/:id)
GET http://localhost:3000/types/2