##########################
#        Request         #
##########################

### Home
GET http://localhost:3000/

### Teams(get /team)
GET http://localhost:3000/teams

### Ajouter une team (post /team)
POST http://localhost:3000/teams
Content-Type: application/json

{
  "name": "Nouvelle équipe",
  "description": "La nouvelle équipe de pokémons @#!6'"
}

### Modal d'une team (get /team/:id)
GET http://localhost:3000/teams/4

### Supprimer une team (delete /team/:id)
DELETE http://localhost:3000/teams/5

### Modifier le nom d'une team (update /team/:id)
PATCH http://localhost:3000/teams/4
Content-Type: application/json

{
  "name": "Team modifié"
}

### Ajouter un pokemon à une team (post /team/:teamId/pokemon/pokemon/:id)
POST http://localhost:3000/teams/4/pokemons/1

### Supprimer un pokemon à une team (post /team/:teamId/pokemon/pokemon/:id)
DELETE http://localhost:3000/teams/4/pokemons/1

##########################

### Pokemons(get /pokemon)
GET http://localhost:3000/pokemons

### Modal d'un pokemon (get /pokemon/:id)
GET http://localhost:3000/pokemons/5

##########################

### Types(get /types)
GET http://localhost:3000/types

### Modal d'un type(get /types/:id)
GET http://localhost:3000/types/2